---
- name: download/unpack consul
  unarchive:
    src: "{{ consul_url }}"
    dest: /usr/local/bin
    remote_src: yes
- name: create consul user
  user:
    name: "{{ consul_user }}"
- name: template consul configuration
  template:
    src: consul.j2
    dest: /etc/consul.d/consul.json
- name: template consul systemd scripts
- name: start consul (bootstrap)
- name: start consul (join cluster)
- name: start consul (unbootstrap)
- name: provision dns names, KV, etc
