- hosts: node0
  vars:
    consul_bootstrap: true
  roles:
  - role: consul
- hosts: node1,node2
  vars:
    consul_bootstrap: false
  roles:
  - role: consul
- hosts: node0
  vars:
    consul_bootstrap: false
  roles:
  - role: consul
