---
consul_version: "1.3.0"
consul_ui_version: 
consul_arch: "linux_amd64"
consul_url: "https://releases.hashicorp.com/consul/{{ consul_version }}/consul_{{ consul_version }}_{{ consul_arch }}.zip"
consul_ui_url:
consul_user: "consul"
consul_configdir: "/etc/consul.d"
consul_server: true
consul_datacenter: "dc1"
consul_datadir: "/var/consul"
consul_ui_dir: "/var/consul/dist"
consul_encrypt: "raaaaaaaand per run"
consul_log_level: "INFO"
consul_enable_syslog: true
consul_bootstrap: false
