- name: register vault operator init output
  shell: vault operator init
  register: vault_init
  environment:
    VAULT_ADDR: "http://127.0.0.1:8200"
- shell: vault operator unseal {{ vault_init.stdout_lines[0].split()[3] }}
  environment:
    VAULT_ADDR: "http://127.0.0.1:8200"
- shell: vault operator unseal {{ vault_init.stdout_lines[1].split()[3] }}
  environment:
    VAULT_ADDR: "http://127.0.0.1:8200"
- shell: vault operator unseal {{ vault_init.stdout_lines[2].split()[3] }}
  environment:
    VAULT_ADDR: "http://127.0.0.1:8200"
- debug:
    var: vault_init.stdout_lines
- debug:
    var: vault_init.stdout_lines[2].split()[3]
