galaxy_info:
  author: dyindude
  description: install and set up golang distribution
  role_name: golang
  company: dyindude.net
  issue_tracker_url: "https://github.com/dyindude/ansible-role-golang"
  license: BSD
  min_ansible_version: 2.6.5
  platforms:
    - name: Ubuntu
      versions:
        - bionic
        - xenial
    - name: Debian
      versions:
        - stretch
        - jessie
  galaxy_tags:
    - golang
    - debian
    - ubuntu
dependencies: []
